export const TECHNOLOGIES = [
    { key: "python", value: "Python" },
    { key: "java", value: "Java" },
    { key: "csharp", value: "C#" },
    { key: "javascript", value: "JavaScript" },
    { key: "htmlcss", value: "HTML/CSS" },
    { key: "django", value: "Django" },
    { key: "nodejs", value: "Node.js" },
    { key: "express", value: "Express.js" },
    { key: "react", value: "React" },
    { key: "angular", value: "Angular" },
    { key: "vue", value: "Vue.js" },
    { key: "php", value: "PHP" },
    { key: "ai", value: "Artificial Intelligence" },
    { key: "ml", value: "Machine Learning" },
    { key: "blockchain", value: "Blockchain" },
    { key: "datastructures", value: "Data Structures" },
    { key: "databases", value: "Databases" },
    { key: "android", value: "Android App Development" },
    { key: "ios", value: "iOS App Development" },
    { key: "unity", value: "Unity Game Development" },
    { key: "webdev", value: "Web Development" },
    { key: "iot", value: "Internet of Things (IoT)" },
    { key: "cloudcomputing", value: "Cloud Computing" },
    { key: "cybersecurity", value: "Cybersecurity" },
    { key: "bigdata", value: "Big Data" },
];
